### ISSUE TITLE
Accessing sparql query string externally

### ISSUE THREAD

**Issue by garychen319** [miguel76/SparqlBlocks#5]
Is there a way to access the sparql query generated from sparqlblocks externally? For eg. I want to display it within the page rather than saving it to a file.

**Comment by miguel76** [comment]
Currently the user interface does not provide a way to see the SPARQL query in the same page.
What you can do, apart from saving it, is seeing the query in YASGUI (using the command "Open Query in YASGUI").
Regarding the code, each query block object has the property `sparqlQueryStr` that holds the current generated SPARQL query.
I would not thus be difficult to add a way of showing it in the page itself.

**Comment by miguel76** [comment]
I close the issue because it was actually a question. Please create a new issue if you want to propose a specific feature.
